### ISSUE TITLE
How to open PDF when succeed to build

### ISSUE THREAD

**Issue by kikirinrin** [Paperist/docker-alpine-texlive-ja#2]
Thank you for developing a great container. It worked and a pdf file was created.
But would you tell me how can I open the pdf file from docker image (I'm a novice of Docker, so excuse me for asking a stupid question)?

I compiled `example.tex` from a shell script like

`platex example`
`pbibtex example`
`platex example`
`platex example`
`dvipdfmx example`
`open example.pdf`.

The last command containing `open` command fails because the command did not work in the docker image.

What command should I use to open a file in the image?
I found a word `linux` in the Dockerfile, so I tested
- `xgd-open`
- `evince-open`
- `gnome-open`
- etc...
but none of them worked.

**Comment by 3846masa** [comment]
Docker container cannot access to host machine, so it is no way to open PDF from container.

However, you can save PDF to host machine using volume mount.
I think using docker-compose.yml is easier way.

## Using docker-compose.yml

First, make `docker-compose.yml` into your working directory.
```yml
version: '2'
services:
  build:
    image: paperist/alpine-texlive-ja
    volumes:
      - './:/workdir'
    command: |
        platex example &&
        pbibtex example &&
        platex example &&
        platex example &&
        dvipdfmx example
```

Next, when you build, type `docker-compose run --rm build && open example.pdf`

----

## Tips

### Latexmk

This image contains `latexmk` command.
`latexmk` is simple and useful command for building.
See http://mg.readthedocs.io/latexmk.html.

First, you put `latexmkrc` like below to your working directory.
```
$latex = 'platex -halt-on-error -interaction=nonstopmode';
$bibtex = 'pbibtex';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'pmendex %O -o %D %S';
$pdf_mode = 3;
$bibtex_use = 2;
```

Next, rewrite `docker-compose.yml` to use latekmk.

```yml
version: '2'
services:
  latexmk:
    image: paperist/alpine-texlive-ja
    volumes:
      - './:/workdir'
    entrypoint: latexmk
```

When you build, type `docker-compose run --rm latexmk example.tex && open example.pdf`
When cleanup, type `docker-compose run --rm latexmk -C example.tex`

### whalebrew

If your machine is macOS or linux, you can use `whalebrew`.
`whalebrew` enables to use docker image like command.

First, install `whalebrew` ( see https://github.com/bfirsh/whalebrew#install )

Next, type `whalebrew install paperist/latexmk`.
( Docker image from https://github.com/Paperist/whalebrew-latexmk )

When you build, type `latexmk example.tex && open example.pdf`
When cleanup, type `latexmk -C example.tex`

----

I hope that you can write comfortably.
